export const GRID_SIZE = 3;
export const CELL_SIZE = 1;
export const PIECE_OPACITY = 0.95;
export const PIECE_HIGHLIGHT_OPACITY = 0.6;

export const SOMA_PIECES = [
    {
        id: "3",
        name: "3 Shape",
        color: "#FF0000",
        baseShape: [ [0,0,0], [1,0,0], [0,1,0] ]
    },
    {
        id: "l",
        name: "L Shape",
        color: "#00FF00",
        baseShape: [ [0,0,0], [1,0,0], [2,0,0], [0,1,0] ]
    },
    {
        id: "t",
        name: "T Shape",
        color: "#0000FF",
        baseShape: [ [0,0,0], [1,0,0], [2,0,0], [1,1,0] ]
    },
    {
        id: "z",
        name: "Z Shape",
        color: "#FFFF00",
        baseShape: [ [0,0,0], [1,0,0], [1,1,0], [2,1,0] ]
    },
    {
        id: "p",
        name: "Pos step",
        color: "#FF00FF",
        baseShape: [ [0,0,0], [1,0,0], [1,1,0], [1,1,1] ]
    },
    {
        id: "n",
        name: "Neg step",
        color: "#00FFFF",
        baseShape: [ [0,0,0], [1,0,0], [1,0,1], [1,1,1] ]
    },
    {
        id: "c",
        name: "Corner Shape",
        color: "#FFA500",
        baseShape: [ [0,0,0], [1,0,0], [0,1,0], [0,0,1] ]
    }
];

export const VALID_PIECES = new Set(['3', 'l', 't', 'z', 'p', 'n', 'c']);

export const SHAPE_IDS = [
    'alter',
    'apartment_building',
    'arch',
    'arch_high',
    'bathtub',
    'battleship',
    'bb26',
    'bb28',
    'bb59',
    'bench_2',
    'big_3',
    'big_3_w_pips',
    'building',
    'burr',
    'canal',
    'chair',
    'church',
    'clip',
    'corner_notch_cube',
    'cornerstone',
    'cross',
    'crystal',
    'crystal_sticks',
    'crystal_wall',
    'cube',
    'diagonal_b2_plus',
    'diagonal_pins_holes_cube',
    'diamond_wall_plus_3',
    'disassemblable_cube',
    'disassemblable_cube_joined',
    'dog',
    'double_W',
    'double_tower_notch_cube',
    'duck',
    'duck_monument',
    'eiffel', // NOT POSSIBLE
    'elephant',
    'fat_t',
    'fat_w_plus_3',
    'few_permutations_xy',
    'few_permutations_xz',
    'few_permutations_yz',
    'fish_wall',
    'flat_4x4',
    'flat_castle',
    'flat_castle_4x6',
    'flat_castle_bad',
    'flat_castle_base_down',
    'funky_chair',
    'heliport_corner_corner',
    'high_wall',
    'inverse_cross',
    'joined_2_5_tower',
    'knot',
    'long_bed',
    'long_wall',
    'l_p_cube',
    'middle_notch',
    'odd_footing_wall',
    'p',
    'p_dot',
    'paddlewheeler',
    'paddock',
    'poodle',
    'pseudo_symmetric_p_n_cube',
    'pyramid',
    'pyramid2',
    'removed_added_cross',
    'scorpion',
    'separated_stairs_cube',
    'separated_tower',
    'separated_tower_2_5',
    'separated_tower_2_5_no_spaces',
    'separated_tower_3_4',
    'separated_tower_4_3',
    'shell_game',
    'shower_box',
    'shower_box_ud',
    'skyscraper',
    'snake',
    'soma100',
    'soma169',
    'soma169_taller',
    'spinner_wall',
    'swivel_pin',
    'symmetric',
    'symmetric_castle',
    'symmetric_front_back',
    'symmetric_front_back_separated',
    'throne',
    'track',
    'trefoil',
    'tugboat',
    'tunnel',
    'tower',
    'tower_separated',
    'well',
    'well_5',
    'walls_wells_2_001',
    'w_plus_block',
    '003_dog', 
    '15_12_cube',
    '184_cantilevered_cross',
    '1_thick_x',
    '1_thick_y',
    '1_thick_z',
    '2Wb',
    '2Wc',
    '2x3x4+3',
    '2x3x4+3_separated',
    '2x3x5_3holes',
    '2x3x5_half_full_holes',
    '3_notches',
    '3_notches_base_down',
    '3_pin_cube',
    '3_slide_wall',
    '3s_2s_wall',
    '3x3x3_wall',
    '3x3x3_wall_cpn',
    '3x4_3x5',
    '3x5_and_cpn',
    '4x4_center_tower',
    '4x4_corner_tower',
    '5_seat_bench',
    '6x4_flat',
    '8x4_flat',
    'A401425_418_separated'
]; 